# ──────────────────────────────────────────────────────────────────────────────
# Numeric tables for the BFF-vs-deepAFT experiment (right-censored RWD), pooled
# sample.  For each metric (RMSE, Bias, Coverage, Posterior variance) and each
# (lambda_d, lambda_u) cell, report mean and the 2.5%-97.5% interval ACROSS the
# Monte Carlo replications (the spread the boxplots show).
#
# Writes:
#   results_full_table.csv  -- long, machine-readable (mean, sd, mcse, q025, q975)
#   results_sm_tables.tex   -- one booktabs table per metric, ready to \input
# and prints the four metric grids to the console.
# ──────────────────────────────────────────────────────────────────────────────

res_dir <- "simulations/exp2_competitor"
res <- rbind(
  readRDS(file.path(res_dir, "sim_surv_v12_bff_output.rds")),
  readRDS(file.path(res_dir, "sim_surv_v12_deepaft_output.rds"))
)
res <- res[res$population == "All", ]              # pooled evaluation sample

meth      <- c("Fusion", "deepAFT-RCT-S", "deepAFT-RCT-T",
               "deepAFT-Pooled-S", "deepAFT-Pooled-T")
meth_disp <- c("Bayesian fusion forest", "DNN (RCT, S)", "DNN (RCT, T)",
               "DNN (pool, S)", "DNN (pool, T)")
meth_tex  <- c("BFF", "DNN R/S", "DNN R/T", "DNN P/S", "DNN P/T")
metrics     <- c("rmse", "bias", "coverage", "postvar")
metric_labs <- c(rmse = "RMSE", bias = "Bias",
                 coverage = "Coverage", postvar = "Posterior variance")
lds <- c(0, 1, 2); lus <- c(0, 1, 2)

# Drop non-finite values and rare divergent blow-ups (a diverged deepAFT bootstrap
# refit can give a posterior variance ~1e6).  The Q3 + 30*IQR rule is extreme
# enough to catch only genuine numerical artefacts, leaving heavy tails intact.
trim_div <- function(v) {
  v  <- v[is.finite(v)]
  if (length(v) < 4) return(v)
  qs <- quantile(v, c(0.25, 0.75), names = FALSE); iqr <- qs[2] - qs[1]
  if (iqr <= 0) return(v)
  v[v >= qs[1] - 30 * iqr & v <= qs[2] + 30 * iqr]
}

# ── long summary: one row per metric x cell x method ──────────────────────────
long <- do.call(rbind, lapply(metrics, function(mt)
  do.call(rbind, lapply(lds, function(ld) do.call(rbind, lapply(lus, function(lu)
    do.call(rbind, lapply(meth, function(me) {
      v  <- trim_div(res[res$lambda_d == ld & res$lambda_u == lu & res$method == me, mt])
      q  <- quantile(v, c(0.025, 0.975), names = FALSE)
      data.frame(metric = mt, lambda_d = ld, lambda_u = lu, method = me,
                 mean = mean(v), sd = sd(v), mcse = sd(v) / sqrt(length(v)),
                 q2.5 = q[1], q97.5 = q[2], n = length(v),
                 stringsAsFactors = FALSE)
    })))))))
)
csv_path <- file.path(res_dir, "results_full_table.csv")
write.csv(long, csv_path, row.names = FALSE)
cat("Wrote", csv_path, "\n")

# ── console: one wide grid per metric (rows = cell, cols = method) ────────────
fmt <- function(m, lo, hi) sprintf("%.3f [%.3f, %.3f]", m, lo, hi)
for (mt in metrics) {
  sub <- long[long$metric == mt, ]
  wide <- data.frame(lambda_d = integer(0), lambda_u = integer(0))
  rows <- lapply(seq_len(nrow(unique(sub[c("lambda_d", "lambda_u")]))), function(i) NULL)
  grid <- unique(sub[c("lambda_d", "lambda_u")])
  cells <- lapply(seq_len(nrow(grid)), function(i) {
    ld <- grid$lambda_d[i]; lu <- grid$lambda_u[i]
    r  <- data.frame(lambda_d = ld, lambda_u = lu)
    for (k in seq_along(meth)) {
      s <- sub[sub$lambda_d == ld & sub$lambda_u == lu & sub$method == meth[k], ]
      r[[meth_tex[k]]] <- fmt(s$mean, s$q2.5, s$q97.5)
    }
    r
  })
  wide <- do.call(rbind, cells)
  cat(sprintf("\n=== %s  (mean [2.5%%, 97.5%%] over %d reps; pooled sample) ===\n",
              metric_labs[[mt]], max(long$n)))
  print(wide, row.names = FALSE)
}

# ── LaTeX: one booktabs table per metric ──────────────────────────────────────
tex <- c("% Auto-generated by tables_bff_dnn.R -- BFF vs deep-AFT, pooled sample.",
         "% Each cell: mean [2.5%, 97.5%] across Monte Carlo replications.",
         "% Requires \\usepackage{booktabs}.")
for (mt in metrics) {
  sub  <- long[long$metric == mt, ]
  grid <- unique(sub[c("lambda_d", "lambda_u")])
  tex <- c(tex, "",
           "\\begin{table}[tb]", "  \\centering",
           sprintf("  \\caption{%s of $\\hat\\tau(x)$ on the pooled sample, by source-deviation strength $\\lambda_d$ and confounding strength $\\lambda_u$. Each entry is the mean over Monte Carlo replications with the $2.5$--$97.5\\%%$ replication interval in brackets.}",
                   metric_labs[[mt]]),
           sprintf("  \\label{tab:sm-%s}", mt),
           "  \\begin{tabular}{@{}ll rrrrr@{}}", "    \\toprule",
           paste0("    $\\lambda_d$ & $\\lambda_u$ & ",
                  paste(meth_tex, collapse = " & "), " \\\\"),
           "    \\midrule")
  for (i in seq_len(nrow(grid))) {
    ld <- grid$lambda_d[i]; lu <- grid$lambda_u[i]
    cellstr <- sapply(meth, function(me) {
      s <- sub[sub$lambda_d == ld & sub$lambda_u == lu & sub$method == me, ]
      sprintf("%.3f [%.3f, %.3f]", s$mean, s$q2.5, s$q97.5)
    })
    tex <- c(tex, sprintf("    %g & %g & %s \\\\", ld, lu,
                          paste(cellstr, collapse = " & ")))
  }
  tex <- c(tex, "    \\bottomrule", "  \\end{tabular}", "\\end{table}")
}
tex_path <- file.path(res_dir, "results_sm_tables.tex")
writeLines(tex, tex_path)
cat("\nWrote", tex_path, "\n")
