// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FusionForest_cpp
Rcpp::List FusionForest_cpp(SEXP nSEXP, SEXP p_treatSEXP, SEXP p_controlSEXP, SEXP X_train_treatSEXP, SEXP X_train_controlSEXP, SEXP ySEXP, SEXP status_indicatorSEXP, SEXP is_survivalSEXP, SEXP observed_left_timeSEXP, SEXP observed_right_timeSEXP, SEXP interval_censoring_indicatorSEXP, SEXP treatment_indicatorSEXP, SEXP source_indicatorSEXP, SEXP n_testSEXP, SEXP X_test_controlSEXP, SEXP X_test_treatSEXP, SEXP X_test_deconfSEXP, SEXP treatment_indicator_testSEXP, SEXP source_indicator_testSEXP, SEXP n_deconfSEXP, SEXP p_deconfSEXP, SEXP X_train_deconfSEXP, SEXP no_trees_deconfSEXP, SEXP power_deconfSEXP, SEXP base_deconfSEXP, SEXP p_grow_deconfSEXP, SEXP p_prune_deconfSEXP, SEXP omega_deconfSEXP, SEXP no_trees_treatSEXP, SEXP power_treatSEXP, SEXP base_treatSEXP, SEXP p_grow_treatSEXP, SEXP p_prune_treatSEXP, SEXP omega_treatSEXP, SEXP no_trees_controlSEXP, SEXP power_controlSEXP, SEXP base_controlSEXP, SEXP p_grow_controlSEXP, SEXP p_prune_controlSEXP, SEXP omega_controlSEXP, SEXP sigma_knownSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP nuSEXP, SEXP N_postSEXP, SEXP N_burnSEXP, SEXP store_posterior_sampleSEXP, SEXP verboseSEXP, SEXP treatment_codingSEXP, SEXP propensity_trainSEXP, SEXP propensity_testSEXP, SEXP mixture_modeSEXP, SEXP mixture_KSEXP, SEXP mixture_prior_atom_varianceSEXP, SEXP mixture_mass_initSEXP);
RcppExport SEXP _FusionForests_FusionForest_cpp(SEXP nSEXPSEXP, SEXP p_treatSEXPSEXP, SEXP p_controlSEXPSEXP, SEXP X_train_treatSEXPSEXP, SEXP X_train_controlSEXPSEXP, SEXP ySEXPSEXP, SEXP status_indicatorSEXPSEXP, SEXP is_survivalSEXPSEXP, SEXP observed_left_timeSEXPSEXP, SEXP observed_right_timeSEXPSEXP, SEXP interval_censoring_indicatorSEXPSEXP, SEXP treatment_indicatorSEXPSEXP, SEXP source_indicatorSEXPSEXP, SEXP n_testSEXPSEXP, SEXP X_test_controlSEXPSEXP, SEXP X_test_treatSEXPSEXP, SEXP X_test_deconfSEXPSEXP, SEXP treatment_indicator_testSEXPSEXP, SEXP source_indicator_testSEXPSEXP, SEXP n_deconfSEXPSEXP, SEXP p_deconfSEXPSEXP, SEXP X_train_deconfSEXPSEXP, SEXP no_trees_deconfSEXPSEXP, SEXP power_deconfSEXPSEXP, SEXP base_deconfSEXPSEXP, SEXP p_grow_deconfSEXPSEXP, SEXP p_prune_deconfSEXPSEXP, SEXP omega_deconfSEXPSEXP, SEXP no_trees_treatSEXPSEXP, SEXP power_treatSEXPSEXP, SEXP base_treatSEXPSEXP, SEXP p_grow_treatSEXPSEXP, SEXP p_prune_treatSEXPSEXP, SEXP omega_treatSEXPSEXP, SEXP no_trees_controlSEXPSEXP, SEXP power_controlSEXPSEXP, SEXP base_controlSEXPSEXP, SEXP p_grow_controlSEXPSEXP, SEXP p_prune_controlSEXPSEXP, SEXP omega_controlSEXPSEXP, SEXP sigma_knownSEXPSEXP, SEXP sigmaSEXPSEXP, SEXP lambdaSEXPSEXP, SEXP nuSEXPSEXP, SEXP N_postSEXPSEXP, SEXP N_burnSEXPSEXP, SEXP store_posterior_sampleSEXPSEXP, SEXP verboseSEXPSEXP, SEXP treatment_codingSEXPSEXP, SEXP propensity_trainSEXPSEXP, SEXP propensity_testSEXPSEXP, SEXP mixture_modeSEXPSEXP, SEXP mixture_KSEXPSEXP, SEXP mixture_prior_atom_varianceSEXPSEXP, SEXP mixture_mass_initSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nSEXP(nSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_treatSEXP(p_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_controlSEXP(p_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_treatSEXP(X_train_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_controlSEXP(X_train_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type status_indicatorSEXP(status_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type is_survivalSEXP(is_survivalSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type observed_left_timeSEXP(observed_left_timeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type observed_right_timeSEXP(observed_right_timeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type interval_censoring_indicatorSEXP(interval_censoring_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicatorSEXP(treatment_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_indicatorSEXP(source_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_testSEXP(n_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_controlSEXP(X_test_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_treatSEXP(X_test_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_deconfSEXP(X_test_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicator_testSEXP(treatment_indicator_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_indicator_testSEXP(source_indicator_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_deconfSEXP(n_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_deconfSEXP(p_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_deconfSEXP(X_train_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_deconfSEXP(no_trees_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_deconfSEXP(power_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_deconfSEXP(base_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_deconfSEXP(p_grow_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_deconfSEXP(p_prune_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_deconfSEXP(omega_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_treatSEXP(no_trees_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_treatSEXP(power_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_treatSEXP(base_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_treatSEXP(p_grow_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_treatSEXP(p_prune_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_treatSEXP(omega_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_controlSEXP(no_trees_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_controlSEXP(power_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_controlSEXP(base_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_controlSEXP(p_grow_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_controlSEXP(p_prune_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_controlSEXP(omega_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_knownSEXP(sigma_knownSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmaSEXP(sigmaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaSEXP(lambdaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nuSEXP(nuSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_postSEXP(N_postSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_burnSEXP(N_burnSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type store_posterior_sampleSEXP(store_posterior_sampleSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboseSEXP(verboseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_codingSEXP(treatment_codingSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type propensity_trainSEXP(propensity_trainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type propensity_testSEXP(propensity_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_modeSEXP(mixture_modeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_KSEXP(mixture_KSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_prior_atom_varianceSEXP(mixture_prior_atom_varianceSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_mass_initSEXP(mixture_mass_initSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(FusionForest_cpp(nSEXP, p_treatSEXP, p_controlSEXP, X_train_treatSEXP, X_train_controlSEXP, ySEXP, status_indicatorSEXP, is_survivalSEXP, observed_left_timeSEXP, observed_right_timeSEXP, interval_censoring_indicatorSEXP, treatment_indicatorSEXP, source_indicatorSEXP, n_testSEXP, X_test_controlSEXP, X_test_treatSEXP, X_test_deconfSEXP, treatment_indicator_testSEXP, source_indicator_testSEXP, n_deconfSEXP, p_deconfSEXP, X_train_deconfSEXP, no_trees_deconfSEXP, power_deconfSEXP, base_deconfSEXP, p_grow_deconfSEXP, p_prune_deconfSEXP, omega_deconfSEXP, no_trees_treatSEXP, power_treatSEXP, base_treatSEXP, p_grow_treatSEXP, p_prune_treatSEXP, omega_treatSEXP, no_trees_controlSEXP, power_controlSEXP, base_controlSEXP, p_grow_controlSEXP, p_prune_controlSEXP, omega_controlSEXP, sigma_knownSEXP, sigmaSEXP, lambdaSEXP, nuSEXP, N_postSEXP, N_burnSEXP, store_posterior_sampleSEXP, verboseSEXP, treatment_codingSEXP, propensity_trainSEXP, propensity_testSEXP, mixture_modeSEXP, mixture_KSEXP, mixture_prior_atom_varianceSEXP, mixture_mass_initSEXP));
    return rcpp_result_gen;
END_RCPP
}
// FusionForest4_cpp
Rcpp::List FusionForest4_cpp(SEXP nSEXP, SEXP p_treatSEXP, SEXP p_controlSEXP, SEXP X_train_treatSEXP, SEXP X_train_controlSEXP, SEXP ySEXP, SEXP status_indicatorSEXP, SEXP is_survivalSEXP, SEXP observed_left_timeSEXP, SEXP observed_right_timeSEXP, SEXP interval_censoring_indicatorSEXP, SEXP treatment_indicatorSEXP, SEXP source_indicatorSEXP, SEXP n_testSEXP, SEXP X_test_controlSEXP, SEXP X_test_treatSEXP, SEXP X_test_deconfSEXP, SEXP X_test_deviationSEXP, SEXP treatment_indicator_testSEXP, SEXP source_indicator_testSEXP, SEXP n_deconfSEXP, SEXP p_deconfSEXP, SEXP X_train_deconfSEXP, SEXP no_trees_deconfSEXP, SEXP power_deconfSEXP, SEXP base_deconfSEXP, SEXP p_grow_deconfSEXP, SEXP p_prune_deconfSEXP, SEXP omega_deconfSEXP, SEXP n_deviationSEXP, SEXP p_deviationSEXP, SEXP X_train_deviationSEXP, SEXP no_trees_deviationSEXP, SEXP power_deviationSEXP, SEXP base_deviationSEXP, SEXP p_grow_deviationSEXP, SEXP p_prune_deviationSEXP, SEXP omega_deviationSEXP, SEXP no_trees_treatSEXP, SEXP power_treatSEXP, SEXP base_treatSEXP, SEXP p_grow_treatSEXP, SEXP p_prune_treatSEXP, SEXP omega_treatSEXP, SEXP no_trees_controlSEXP, SEXP power_controlSEXP, SEXP base_controlSEXP, SEXP p_grow_controlSEXP, SEXP p_prune_controlSEXP, SEXP omega_controlSEXP, SEXP sigma_knownSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP nuSEXP, SEXP N_postSEXP, SEXP N_burnSEXP, SEXP store_posterior_sampleSEXP, SEXP verboseSEXP, SEXP treatment_codingSEXP, SEXP propensity_trainSEXP, SEXP propensity_testSEXP, SEXP mixture_modeSEXP, SEXP mixture_KSEXP, SEXP mixture_prior_atom_varianceSEXP, SEXP mixture_mass_initSEXP);
RcppExport SEXP _FusionForests_FusionForest4_cpp(SEXP nSEXPSEXP, SEXP p_treatSEXPSEXP, SEXP p_controlSEXPSEXP, SEXP X_train_treatSEXPSEXP, SEXP X_train_controlSEXPSEXP, SEXP ySEXPSEXP, SEXP status_indicatorSEXPSEXP, SEXP is_survivalSEXPSEXP, SEXP observed_left_timeSEXPSEXP, SEXP observed_right_timeSEXPSEXP, SEXP interval_censoring_indicatorSEXPSEXP, SEXP treatment_indicatorSEXPSEXP, SEXP source_indicatorSEXPSEXP, SEXP n_testSEXPSEXP, SEXP X_test_controlSEXPSEXP, SEXP X_test_treatSEXPSEXP, SEXP X_test_deconfSEXPSEXP, SEXP X_test_deviationSEXPSEXP, SEXP treatment_indicator_testSEXPSEXP, SEXP source_indicator_testSEXPSEXP, SEXP n_deconfSEXPSEXP, SEXP p_deconfSEXPSEXP, SEXP X_train_deconfSEXPSEXP, SEXP no_trees_deconfSEXPSEXP, SEXP power_deconfSEXPSEXP, SEXP base_deconfSEXPSEXP, SEXP p_grow_deconfSEXPSEXP, SEXP p_prune_deconfSEXPSEXP, SEXP omega_deconfSEXPSEXP, SEXP n_deviationSEXPSEXP, SEXP p_deviationSEXPSEXP, SEXP X_train_deviationSEXPSEXP, SEXP no_trees_deviationSEXPSEXP, SEXP power_deviationSEXPSEXP, SEXP base_deviationSEXPSEXP, SEXP p_grow_deviationSEXPSEXP, SEXP p_prune_deviationSEXPSEXP, SEXP omega_deviationSEXPSEXP, SEXP no_trees_treatSEXPSEXP, SEXP power_treatSEXPSEXP, SEXP base_treatSEXPSEXP, SEXP p_grow_treatSEXPSEXP, SEXP p_prune_treatSEXPSEXP, SEXP omega_treatSEXPSEXP, SEXP no_trees_controlSEXPSEXP, SEXP power_controlSEXPSEXP, SEXP base_controlSEXPSEXP, SEXP p_grow_controlSEXPSEXP, SEXP p_prune_controlSEXPSEXP, SEXP omega_controlSEXPSEXP, SEXP sigma_knownSEXPSEXP, SEXP sigmaSEXPSEXP, SEXP lambdaSEXPSEXP, SEXP nuSEXPSEXP, SEXP N_postSEXPSEXP, SEXP N_burnSEXPSEXP, SEXP store_posterior_sampleSEXPSEXP, SEXP verboseSEXPSEXP, SEXP treatment_codingSEXPSEXP, SEXP propensity_trainSEXPSEXP, SEXP propensity_testSEXPSEXP, SEXP mixture_modeSEXPSEXP, SEXP mixture_KSEXPSEXP, SEXP mixture_prior_atom_varianceSEXPSEXP, SEXP mixture_mass_initSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nSEXP(nSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_treatSEXP(p_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_controlSEXP(p_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_treatSEXP(X_train_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_controlSEXP(X_train_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type status_indicatorSEXP(status_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type is_survivalSEXP(is_survivalSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type observed_left_timeSEXP(observed_left_timeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type observed_right_timeSEXP(observed_right_timeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type interval_censoring_indicatorSEXP(interval_censoring_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicatorSEXP(treatment_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_indicatorSEXP(source_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_testSEXP(n_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_controlSEXP(X_test_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_treatSEXP(X_test_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_deconfSEXP(X_test_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_deviationSEXP(X_test_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicator_testSEXP(treatment_indicator_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_indicator_testSEXP(source_indicator_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_deconfSEXP(n_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_deconfSEXP(p_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_deconfSEXP(X_train_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_deconfSEXP(no_trees_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_deconfSEXP(power_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_deconfSEXP(base_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_deconfSEXP(p_grow_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_deconfSEXP(p_prune_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_deconfSEXP(omega_deconfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_deviationSEXP(n_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_deviationSEXP(p_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_deviationSEXP(X_train_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_deviationSEXP(no_trees_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_deviationSEXP(power_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_deviationSEXP(base_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_deviationSEXP(p_grow_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_deviationSEXP(p_prune_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_deviationSEXP(omega_deviationSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_treatSEXP(no_trees_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_treatSEXP(power_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_treatSEXP(base_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_treatSEXP(p_grow_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_treatSEXP(p_prune_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_treatSEXP(omega_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_controlSEXP(no_trees_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type power_controlSEXP(power_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type base_controlSEXP(base_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_grow_controlSEXP(p_grow_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_prune_controlSEXP(p_prune_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_controlSEXP(omega_controlSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_knownSEXP(sigma_knownSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmaSEXP(sigmaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaSEXP(lambdaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nuSEXP(nuSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_postSEXP(N_postSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_burnSEXP(N_burnSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type store_posterior_sampleSEXP(store_posterior_sampleSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboseSEXP(verboseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_codingSEXP(treatment_codingSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type propensity_trainSEXP(propensity_trainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type propensity_testSEXP(propensity_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_modeSEXP(mixture_modeSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_KSEXP(mixture_KSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_prior_atom_varianceSEXP(mixture_prior_atom_varianceSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mixture_mass_initSEXP(mixture_mass_initSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(FusionForest4_cpp(nSEXP, p_treatSEXP, p_controlSEXP, X_train_treatSEXP, X_train_controlSEXP, ySEXP, status_indicatorSEXP, is_survivalSEXP, observed_left_timeSEXP, observed_right_timeSEXP, interval_censoring_indicatorSEXP, treatment_indicatorSEXP, source_indicatorSEXP, n_testSEXP, X_test_controlSEXP, X_test_treatSEXP, X_test_deconfSEXP, X_test_deviationSEXP, treatment_indicator_testSEXP, source_indicator_testSEXP, n_deconfSEXP, p_deconfSEXP, X_train_deconfSEXP, no_trees_deconfSEXP, power_deconfSEXP, base_deconfSEXP, p_grow_deconfSEXP, p_prune_deconfSEXP, omega_deconfSEXP, n_deviationSEXP, p_deviationSEXP, X_train_deviationSEXP, no_trees_deviationSEXP, power_deviationSEXP, base_deviationSEXP, p_grow_deviationSEXP, p_prune_deviationSEXP, omega_deviationSEXP, no_trees_treatSEXP, power_treatSEXP, base_treatSEXP, p_grow_treatSEXP, p_prune_treatSEXP, omega_treatSEXP, no_trees_controlSEXP, power_controlSEXP, base_controlSEXP, p_grow_controlSEXP, p_prune_controlSEXP, omega_controlSEXP, sigma_knownSEXP, sigmaSEXP, lambdaSEXP, nuSEXP, N_postSEXP, N_burnSEXP, store_posterior_sampleSEXP, verboseSEXP, treatment_codingSEXP, propensity_trainSEXP, propensity_testSEXP, mixture_modeSEXP, mixture_KSEXP, mixture_prior_atom_varianceSEXP, mixture_mass_initSEXP));
    return rcpp_result_gen;
END_RCPP
}
// SimpleBART_cpp
Rcpp::List SimpleBART_cpp(SEXP nSEXP, SEXP pSEXP, SEXP X_trainSEXP, SEXP ySEXP, SEXP n_testSEXP, SEXP X_testSEXP, SEXP no_treesSEXP, SEXP powerSEXP, SEXP baseSEXP, SEXP p_growSEXP, SEXP p_pruneSEXP, SEXP omegaSEXP, SEXP sigma_knownSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP nuSEXP, SEXP N_postSEXP, SEXP N_burnSEXP, SEXP verboseSEXP, SEXP irsSEXP, SEXP store_posterior_sampleSEXP);
RcppExport SEXP _FusionForests_SimpleBART_cpp(SEXP nSEXPSEXP, SEXP pSEXPSEXP, SEXP X_trainSEXPSEXP, SEXP ySEXPSEXP, SEXP n_testSEXPSEXP, SEXP X_testSEXPSEXP, SEXP no_treesSEXPSEXP, SEXP powerSEXPSEXP, SEXP baseSEXPSEXP, SEXP p_growSEXPSEXP, SEXP p_pruneSEXPSEXP, SEXP omegaSEXPSEXP, SEXP sigma_knownSEXPSEXP, SEXP sigmaSEXPSEXP, SEXP lambdaSEXPSEXP, SEXP nuSEXPSEXP, SEXP N_postSEXPSEXP, SEXP N_burnSEXPSEXP, SEXP verboseSEXPSEXP, SEXP irsSEXPSEXP, SEXP store_posterior_sampleSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nSEXP(nSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pSEXP(pSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_trainSEXP(X_trainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_testSEXP(n_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_testSEXP(X_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_treesSEXP(no_treesSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type powerSEXP(powerSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baseSEXP(baseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_growSEXP(p_growSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_pruneSEXP(p_pruneSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omegaSEXP(omegaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_knownSEXP(sigma_knownSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmaSEXP(sigmaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaSEXP(lambdaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nuSEXP(nuSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_postSEXP(N_postSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_burnSEXP(N_burnSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboseSEXP(verboseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type irsSEXP(irsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type store_posterior_sampleSEXP(store_posterior_sampleSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(SimpleBART_cpp(nSEXP, pSEXP, X_trainSEXP, ySEXP, n_testSEXP, X_testSEXP, no_treesSEXP, powerSEXP, baseSEXP, p_growSEXP, p_pruneSEXP, omegaSEXP, sigma_knownSEXP, sigmaSEXP, lambdaSEXP, nuSEXP, N_postSEXP, N_burnSEXP, verboseSEXP, irsSEXP, store_posterior_sampleSEXP));
    return rcpp_result_gen;
END_RCPP
}
// SimpleBCF_cpp
Rcpp::List SimpleBCF_cpp(SEXP nSEXP, SEXP p_progSEXP, SEXP p_treatSEXP, SEXP X_train_progSEXP, SEXP X_train_treatSEXP, SEXP ySEXP, SEXP treatment_indicatorSEXP, SEXP n_testSEXP, SEXP X_test_progSEXP, SEXP X_test_treatSEXP, SEXP treatment_indicator_testSEXP, SEXP no_trees_progSEXP, SEXP no_trees_treatSEXP, SEXP powerSEXP, SEXP baseSEXP, SEXP p_growSEXP, SEXP p_pruneSEXP, SEXP omega_progSEXP, SEXP omega_treatSEXP, SEXP sigma_knownSEXP, SEXP sigmaSEXP, SEXP lambdaSEXP, SEXP nuSEXP, SEXP N_postSEXP, SEXP N_burnSEXP, SEXP verboseSEXP, SEXP irsSEXP, SEXP store_posterior_sampleSEXP);
RcppExport SEXP _FusionForests_SimpleBCF_cpp(SEXP nSEXPSEXP, SEXP p_progSEXPSEXP, SEXP p_treatSEXPSEXP, SEXP X_train_progSEXPSEXP, SEXP X_train_treatSEXPSEXP, SEXP ySEXPSEXP, SEXP treatment_indicatorSEXPSEXP, SEXP n_testSEXPSEXP, SEXP X_test_progSEXPSEXP, SEXP X_test_treatSEXPSEXP, SEXP treatment_indicator_testSEXPSEXP, SEXP no_trees_progSEXPSEXP, SEXP no_trees_treatSEXPSEXP, SEXP powerSEXPSEXP, SEXP baseSEXPSEXP, SEXP p_growSEXPSEXP, SEXP p_pruneSEXPSEXP, SEXP omega_progSEXPSEXP, SEXP omega_treatSEXPSEXP, SEXP sigma_knownSEXPSEXP, SEXP sigmaSEXPSEXP, SEXP lambdaSEXPSEXP, SEXP nuSEXPSEXP, SEXP N_postSEXPSEXP, SEXP N_burnSEXPSEXP, SEXP verboseSEXPSEXP, SEXP irsSEXPSEXP, SEXP store_posterior_sampleSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type nSEXP(nSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_progSEXP(p_progSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_treatSEXP(p_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_progSEXP(X_train_progSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_train_treatSEXP(X_train_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicatorSEXP(treatment_indicatorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_testSEXP(n_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_progSEXP(X_test_progSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_test_treatSEXP(X_test_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type treatment_indicator_testSEXP(treatment_indicator_testSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_progSEXP(no_trees_progSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type no_trees_treatSEXP(no_trees_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type powerSEXP(powerSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baseSEXP(baseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_growSEXP(p_growSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_pruneSEXP(p_pruneSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_progSEXP(omega_progSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_treatSEXP(omega_treatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_knownSEXP(sigma_knownSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmaSEXP(sigmaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaSEXP(lambdaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nuSEXP(nuSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_postSEXP(N_postSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_burnSEXP(N_burnSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboseSEXP(verboseSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type irsSEXP(irsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type store_posterior_sampleSEXP(store_posterior_sampleSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(SimpleBCF_cpp(nSEXP, p_progSEXP, p_treatSEXP, X_train_progSEXP, X_train_treatSEXP, ySEXP, treatment_indicatorSEXP, n_testSEXP, X_test_progSEXP, X_test_treatSEXP, treatment_indicator_testSEXP, no_trees_progSEXP, no_trees_treatSEXP, powerSEXP, baseSEXP, p_growSEXP, p_pruneSEXP, omega_progSEXP, omega_treatSEXP, sigma_knownSEXP, sigmaSEXP, lambdaSEXP, nuSEXP, N_postSEXP, N_burnSEXP, verboseSEXP, irsSEXP, store_posterior_sampleSEXP));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FusionForests_FusionForest_cpp", (DL_FUNC) &_FusionForests_FusionForest_cpp, 55},
    {"_FusionForests_FusionForest4_cpp", (DL_FUNC) &_FusionForests_FusionForest4_cpp, 65},
    {"_FusionForests_SimpleBART_cpp", (DL_FUNC) &_FusionForests_SimpleBART_cpp, 21},
    {"_FusionForests_SimpleBCF_cpp", (DL_FUNC) &_FusionForests_SimpleBCF_cpp, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_FusionForests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
